import os
import re
import pandas as pd
import numpy as np
from openai import OpenAI
import torch
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from modules.geom_autoencoder import GeomVAE, EncoderwithPredictionHead
from modules.submodules import LatticeNormalizer
from utils.llm_utils import graph_to_text, parse_graph

# System Prompts for each Agent

PROMPT_DESIGNER_INIT = """
You are a Metamaterial Architect (Designer Agent). 
Your goal is to translate a user's vague design requirement into a highly detailed, technical engineering specification for a 3D lattice structure.
Focus on: unit cell topology (e.g., Octet, Kelvin, TPMS), approximate relative density, symmetry groups, and connectivity rules.
Do not output coordinates yet, just the descriptive specification.
"""

PROMPT_DESIGNER_REFINE = """
You are a Metamaterial Architect (Designer Agent).
You previously proposed a design specification. 
The Supervisor Agent gave it a low score and provided feedback.
Refine your technical specification to address the feedback and better match the user's intent.
"""

PROMPT_SUPERVISOR = """
You are a Senior Metamaterial Scientist (Supervisor Agent).
Your task is to evaluate a "Technical Specification" generated by a Designer Agent against a "User Requirement".

Output Format must be exactly:
Score: <float between 0.0 and 1.0>
Feedback: <Short critique on why it matches or fails, and what is missing>

Criteria:
- Is the specification feasible?
- Does it address the user's specific needs (stiffness, absorption, etc.)?
- Is it detailed enough for a Generator to build coordinates from?
"""

PROMPT_GENERATOR = """
You are a Computational Geometry Engine (Generator Agent).
Your task is to convert a text-based "Technical Specification" into a concrete 3D graph representation.
You must output the result in a specific text block format. 
Ensure the nodes are normalized 3D fractional coordinates (0 to 1).

Output STRICTLY in this format:
~~~
Node number: <N>
Node coordinates:
(x0, y0, z0)
...
(xN-1, yN-1, zN-1)

Edges:
(i0, j0)
...
(iM-1, jM-1)
~~~
Lattice lengths: [a, b, c]
Lattice angles: [α, β, γ]
"""

PROMPT_STRUCTURE_EVALUATE = """
You are a metamaterial scientist specializing in structural design and mechanical characterization. You are fluent in the geometry and typical property ranges of canonical 3-D architectures such as octet-truss, BCC, SC, Kelvin cell, Diamond, and TPMS families.

Task
-----

Given one design prompt and a corresponding metamaterial structure, output:

Score - a single real number in [0, 1] evaluating how well the structure fulfills the design prompt (0 = poor, 1 = perfect).

Input Format
------------

Prompt: <free-text design requirement>

Structure:
~~~
Node number: <N>
Node coordinates:
(x1, y1, z1)
...
(xN, yN, zN)

Edges:
(i0, j0)
...
(iM, jM)
~~~

Lattice lengths: [a, b, c]
Lattice angles: [alpha, beta, gamma]

Output Format
-------------

Score: <float in [0,1]>

Constraints
-----------

- Return only the field specified above, in the exact order and layout.
- Provide no additional commentary, explanations, or reasoning steps.
"""

class PureLLMMetamaterialAgents:
    def __init__(self, api_key, model='gpt-4o-mini', max_iterations=3, threshold=0.5,
                 root='.', ckpt_dir='checkpoints/vae_cond_128_beta001_dis_same_100_frac',
                 device=None, latent_dim=128, condition_dim=12):
        self.client = OpenAI(api_key=api_key)
        self.model = model
        self.max_iterations = max_iterations
        self.threshold = threshold
        self.root = root
        self.ckpt_dir = ckpt_dir
        self.device = device or ('cuda' if torch.cuda.is_available() else 'cpu')
        self.latent_dim = latent_dim
        self.condition_dim = condition_dim
        self.normalizer = LatticeNormalizer()
        self.Predictor = self._load_predictor()

    def _load_predictor(self):
        predictor = EncoderwithPredictionHead(
            GeomVAE(
                self.normalizer,
                max_node_num=100,
                latent_dim=self.latent_dim,
                edge_sample_threshold=0.5,
                is_variational=True,
                is_disent_variational=True,
                is_condition=True,
                condition_dim=self.condition_dim,
                disentangle_same_layer=True,
            ),
            self.latent_dim,
            self.condition_dim,
        )
        predictor.load_state_dict(
            torch.load(
                os.path.join(self.root, self.ckpt_dir, 'best_predictor_model.pt'),
                map_location=self.device,
            )
        )
        predictor = predictor.to(self.device)
        predictor.eval()
        self.normalizer = predictor.AEmodel.normalizer
        return predictor

    def _call_llm(self, system_prompt, user_content, model=None):
        response = self.client.chat.completions.create(
            model=self.model if model is None else model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content}
            ],
            # temperature=0.5
        )
        return response.choices[0].message.content

    def designer_step(self, user_requirement, feedback=None, previous_spec=None):
        if feedback is None:
            # Initial Design
            prompt = f"User Requirement: {user_requirement}\n\nProvide a detailed technical specification."
            return self._call_llm(PROMPT_DESIGNER_INIT, prompt)
        else:
            # Refinement Step
            prompt = (f"User Requirement: {user_requirement}\n"
                      f"Previous Spec: {previous_spec}\n"
                      f"Supervisor Feedback: {feedback}\n\n"
                      f"Generate a refined technical specification.")
            return self._call_llm(PROMPT_DESIGNER_REFINE, prompt)

    def supervisor_step(self, user_requirement, current_spec):
        prompt = (f"User Requirement: {user_requirement}\n"
                  f"Proposed Technical Specification: {current_spec}\n\n"
                  f"Evaluate this.")
        output = self._call_llm(PROMPT_SUPERVISOR, prompt)
        
        # Parse Score and Feedback
        try:
            score_match = re.search(r"Score:\s*([0-9]*\.?[0-9]+)", output)
            score = float(score_match.group(1)) if score_match else 0.0
            feedback = output.split("Feedback:")[-1].strip()
        except Exception as e:
            print(f"Error parsing supervisor output: {e}")
            score = 0.0
            feedback = "Parse error in supervisor output."
            
        return score, feedback

    def generator_step(self, refined_spec):
        prompt = f"Technical Specification: {refined_spec}\n\nGenerate the lattice structure block."
        return self._call_llm(PROMPT_GENERATOR, prompt)

    def structure_evaluation_step(self, structured_input, model=None):
        output = self._call_llm(PROMPT_STRUCTURE_EVALUATE, structured_input, model=model)

        score_match = re.search(r"Score:\s*([0-9]*\.?[0-9]+)", output)
        return float(score_match.group(1)) if score_match else 0.0

    def predict_properties(self, structure_text):
        z, coords, edge_index, batch, lengths, angles, num_atoms = parse_graph(structure_text)
        z = z.to(self.device)
        coords = coords.to(self.device)
        edge_index = edge_index.to(self.device)
        batch = batch.to(self.device)
        lengths = lengths.to(self.device)
        angles = angles.to(self.device)
        num_atoms = num_atoms.to(self.device)
        lengths_normed, angles_normed = self.normalizer(lengths, angles)
        with torch.no_grad():
            pred_y = self.Predictor(
                z, coords, edge_index, batch, lengths_normed, angles_normed, num_atoms, denormalize=True
            ).detach().cpu()
        properties = {
            "Young's modulus": pred_y[:, :3],
            "Shear modulus": pred_y[:, 3:6],
            "Poisson ratio": pred_y[:, 6:],
        }
        return properties, lengths.cpu(), angles.cpu()

    def parse_and_save(self, generator_output, save_path):
        """
        Parses the specific text format and saves to npz.
        """
        try:
            # Extract the block between ~~~
            block_match = re.search(r"~~~(.*?)~~~", generator_output, re.DOTALL)
            if not block_match:
                content = generator_output.strip()
            else:
                content = block_match.group(1).strip()
            
            # Parse Coordinates
            coord_pattern = r"\(([\d\.\-e]+),\s*([\d\.\-e]+),\s*([\d\.\-e]+)\)"
            coords_matches = re.findall(coord_pattern, content.split("Edges:")[0])
            coords = np.array(coords_matches, dtype=float)
            
            # Parse Edges
            edge_section = content.split("Edges:")[1]
            edge_pattern = r"\(([\d]+),\s*([\d]+)\)"
            edge_matches = re.findall(edge_pattern, edge_section)
            edges = np.array(edge_matches, dtype=int).T # Transpose for standard edge_index format
            
            # Parse Lattice Params (outside the ~~~ block usually, or at the end)
            # Looking at prompt requirement, they are after the block
            rest_of_text = generator_output.split("~~~")[-1]
            
            len_match = re.search(r"Lattice lengths:\s*\[([\d\.\,\s]+)\]", rest_of_text)
            ang_match = re.search(r"Lattice angles:\s*\[([\d\.\,\s]+)\]", rest_of_text)
            
            lengths = np.fromstring(len_match.group(1), sep=',') if len_match else np.array([1.0, 1.0, 1.0])
            angles = np.fromstring(ang_match.group(1), sep=',') if ang_match else np.array([90.0, 90.0, 90.0])
            
            # Save
            np.savez(
                save_path,
                frac_coords=coords,
                edge_index=edges,
                lengths=lengths,
                angles=angles,
                atom_types=np.ones(len(coords)) # Dummy types
            )
            print(f"Successfully saved lattice to {save_path}")
            return coords, edges, lengths, angles
            
        except Exception as e:
            print(f"Error parsing generator output: {e}")
            print("Raw Output snippet:", generator_output[:500])
            return None

    def run(self, user_requirement, save_dir='./results', id=0):
        print(f"--- Starting Design for: {user_requirement} ---")
        
        # 1. Designer & Supervisor Loop
        current_spec = self.designer_step(user_requirement)
        score = 0.0
        iteration = 0
        
        while score < self.threshold and iteration < self.max_iterations:
            iteration += 1
            score, feedback = self.supervisor_step(user_requirement, current_spec)
            print(f"Iter {iteration}: Score={score:.2f} | Feedback: {feedback}")
            
            if score < self.threshold:
                print("Refining prompt...")
                current_spec = self.designer_step(user_requirement, feedback, current_spec)
        
        # if score < self.threshold:
        #     print("Warning: Max iterations reached without meeting threshold.")
        # else:
        #     print("Threshold met. Proceeding to Generation.")

        # 2. Generator Step
        print("Generating Structure...")
        raw_structure_text = self.generator_step(current_spec)
        
        # 3. Save
        os.makedirs(save_dir, exist_ok=True)
        filename = f"llm_lattice_{iteration}-{id}.npz"
        save_path = os.path.join(save_dir, filename)
        # print(raw_structure_text)  # Print first 500 characters of raw structure text
        coords, edges, lengths, angles = self.parse_and_save(raw_structure_text, save_path) if self.parse_and_save(raw_structure_text, save_path) is not None else (None, None, None, None)
        properties = self.predict_properties(raw_structure_text)[0]
        supervisor_input_text = construct_supervisor_input(prompt=user_requirement, structure=raw_structure_text, properties=properties) 

        structure_score = self.structure_evaluation_step(supervisor_input_text)
        print(f"Generated structure score: {structure_score:.2f}")
        return current_spec, raw_structure_text, structure_score


def construct_supervisor_input(prompt, structure, lattice_lengths=None, lattice_angles=None, properties=None):
    """
    Constructs the input for the supervisor model by combining the prompt,
    structure, and optional properties.

    Args:
        prompt (str): The prompt text.
        structure (str): The structure text.
        properties (str, optional): The properties text. Defaults to None.

    Returns:
        str: The combined input string.
    """
    input_text = f"Prompt: {prompt}\n\nStructure: {structure}\n"
    if lattice_lengths is None and lattice_angles is None:
        input_text += "\nLattice lengths: [1.0, 1.0, 1.0]\nLattice angles: [90.0, 90.0, 90.0]\n"
    else:
        input_text += f"\nLattice lengths: {lattice_lengths}\nLattice angles: {lattice_angles}"
    if properties is not None:
        input_text += "\nProperties:"
        for key, value in properties.items():
            if isinstance(value, torch.Tensor):
                value = value.tolist()
            input_text += f"\n{key}: {value}"
    return input_text


def evaluate_from_files():
    api_key = os.environ.get("OPENAI_API_KEY", "")
    if not api_key:
        raise ValueError("OPENAI_API_KEY environment variable is required for evaluation.")

    results_dir = "./results/modal_prompt_mix_gpt-504"
    prompts_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "metamaterial_design_prompts.csv",
    )
    output_csv = os.path.join(results_dir, "evaluation_from_files.csv")

    prompts_df = pd.read_csv(prompts_path, header=None)
    agent_system = PureLLMMetamaterialAgents(api_key=api_key)

    try:
        npz_files = sorted(
            [
                f for f in os.listdir(results_dir)
                if f.endswith(".npz") 
            ],
            key=lambda name: int(name.rsplit("-", 1)[-1].split(".")[0]),
        )
    except:
        npz_files = os.listdir(results_dir)

    score_rows = []
    total_score = 0.0

    for filename in npz_files:
        # file_id = int(filename.rsplit("-", 1)[-1].split(".")[0])
        file_id = int(re.search(r'_(\d+)\.npz$', filename).group(1)) if re.search(r'_(\d+)\.npz$', filename) else None
        
        if file_id is None or file_id >= len(prompts_df):
            continue

        npz_path = os.path.join(results_dir, filename)
        with np.load(npz_path) as lattice_data:
            coords = torch.from_numpy(lattice_data["frac_coords"]).float()
            edges = torch.from_numpy(lattice_data["edge_index"]).long()
            lengths = lattice_data["lengths"].tolist()
            angles = lattice_data["angles"].tolist()

        structure_text = graph_to_text(coords, edges)
        structure_with_lattice = (
            f"{structure_text}\nLattice lengths: {lengths}\nLattice angles: {angles}"
        )
        properties = agent_system.predict_properties(structure_with_lattice)[0]
        prompt = prompts_df.iloc[file_id, 0]
        supervisor_input_text = construct_supervisor_input(
            prompt=prompt,
            structure=structure_text,
            lattice_lengths=lengths,
            lattice_angles=angles,
            properties=properties,
        )

        # structure_score = agent_system.structure_evaluation_step(supervisor_input_text, model='gpt-5.4')
        
        client = OpenAI(api_key=api_key)
        response = client.responses.create(
            model="gpt-4.1",
            # reasoning={"effort": "low"},
            instructions=PROMPT_STRUCTURE_EVALUATE,
            input=supervisor_input_text,
        )
        output = response.output_text
        score_match = re.search(r"Score:\s*([0-9]*\.?[0-9]+)", output)
        structure_score = float(score_match.group(1)) if score_match else 0.0
        
        total_score += structure_score
        score_rows.append(
            {
                "index": file_id,
                "file": filename,
                "prompt": prompt,
                "structure_score": structure_score,
            }
        )
        print(f"{file_id}=====>{filename} | structure_score={structure_score:.2f}")

    os.makedirs(results_dir, exist_ok=True)
    pd.DataFrame(score_rows).to_csv(output_csv, index=False)
    average_score = total_score / len(score_rows) if score_rows else 0.0
    print(f"Saved structure scores to {output_csv}")
    print(f"Overall average structure score: {average_score:.4f}")
    return pd.DataFrame(score_rows)



# --- Usage Example ---
if __name__ == "__main__":
    # Set your key
    evaluate_from_files()
    
    exit()
    api_key = os.environ.get("OPENAI_API_KEY", "")
    
    agent_system = PureLLMMetamaterialAgents(api_key=api_key)
    
    
    prompts_df = pd.read_csv('/home/grads/jianpengc/projects/materials/MetaSymbO/metamaterial_design_prompts.csv', header=None)
    results_dir = "./results/pure_llm_prompt"
    output_csv = os.path.join(results_dir, "evaluation.csv")
    score_rows = []
    total_score = 0.0

    for i in range(27, len(prompts_df)):
        input_req = prompts_df.loc[i].values[0]
        
        spec, struct, structure_score = agent_system.run(input_req, save_dir=results_dir, id=i)
        total_score += structure_score
        score_rows.append({
            "index": i,
            "prompt": input_req,
            "structure_score": structure_score,
        })
        print(f"{i}=====>{spec} | structure_score={structure_score:.2f}")

    os.makedirs(results_dir, exist_ok=True)
    pd.DataFrame(score_rows).to_csv(output_csv, index=False)
    average_score = total_score / len(score_rows) if score_rows else 0.0
    print(f"Saved structure scores to {output_csv}")
    print(f"Overall average structure score: {average_score:.4f}")
